---
- name: Install etcd apt package
  become: true
  apt:
    name: etcd
    state: latest

- name: Write etcd configuration
  become: true
  template:
    src: etcd.j2
    dest: /etc/default/etcd
    owner: root
    group: root

- name: Start etcd service
  become: true
  service:
    name: etcd
    state: restarted
