version: '3.2'
services:
  slurmctld:
    hostname: slurmctld
    image: openmole/slurmctld:latest
    volumes:
      - ./conf:/usr/local/etc/
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 1
          memory: 128M
    ports:
      - "2222:22"
    networks:
      - slurm
  slurmd:
    hostname: slurmd
    image: openmole/slurmd:latest
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 1
          memory: 128M
    volumes:
      - ./conf:/usr/local/etc/
    networks:
      - slurm
networks:
  slurm:
