---

- name: Get Ubuntu distribution version
  command: lsb_release -cs
  register: ubuntu_version

- name: Install Docker prerequisites
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu_version.stdout}} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
