---

- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Check for python
      raw: type python > /dev/null
      register: p
      changed_when: false
      failed_when: not (p.rc == 0 or p.rc == 127)


    - name: Install python
      raw: apt-get update && apt-get install python -y
      when: not p.rc == 0

- name: Install etcd
  hosts: etcd_nodes
  roles:
    - role: etcd

- name: Install Docker
  hosts: workers
  become: true
  roles:
    - role: docker

- name: Install Kubernetes
  hosts: workers
  roles:
    - role: kubernetes
